### Initilise race
#@no-log
POST http://localhost:5000/race
Content-Type: application/json

{"trackname":"Silverstone","country":"UK","scheduledstarttime": "2021-02-09T21:05:24Z","cars":[{"team": "Mercedes","driver": "Lewis Hamilton"}], "title": "British GP 2021222efp"}

> {% client.global.set("location",response.headers.valueOf("location")) %}

### Start race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "start"}

### Restart race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "restart"}

### Red flag race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "redflag"}

### Open pit lane
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "openpitlane"}

### Close pit lane
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "closepitlane"}

### Stop race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "stopkk"}

### Change start time
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "delay","proposedracestarttime": "2021-02-09T21:05:24Z"}

### Get a race 
#@no-log
GET {{location}}


### f
OPTIONS {{location}}

### f
HEAD {{location}}
