### Initilise race
#@no-log
POST http://localhost:5000/race
Content-Type: application/json

{"trackname":"Silverstone","country":"UK","scheduledstarttime": "2021-02-09T21:05:24Z", "title": "French GP 2021"}

> {% client.global.set("location",response.headers.valueOf("location")) %}

### Start race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "start"}

### Restart race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "restart"}

### Red flag race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "redflag"}

### Open pit lane
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "openpitlane"}

### Close pit lane
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "closepitlane"}

### Stop race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "stopkk"}

### Change start time
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "delay","proposedracestarttime": "2021-02-09T21:05:24Z"}

### Get a race 
#@no-log
GET {{location}}


### f
OPTIONS {{location}}

### f
HEAD {{location}}


### l

OPTIONS http://localhost:5000/race

### Get a race's cars
#@no-log
GET {{location}}/cars

### Register cars
#@no-log

POST {{location}}/cars
Content-Type: application/json

{"cars":[{"team": "Ferrari","driverid": "01784a41-7182-4a81-8d5b-00746ecc131a"}]}

### Get a car
#@no-log
GET {{location}}/cars/e21ab06a-3473-41d6-b3ab-12768de2df88

### Register driver
#@no-log
POST http://localhost:5000/drivers
Content-Type: application/json

{"name": "Lewis Hamilton"}

### Get drivers
#@no-log
GET http://localhost:5000/drivers

### Get driver
#@no-log
GET http://localhost:5000/drivers/0177ba18-975b-4570-a24c-e2c69a651160

### Car enters pit lane
#@no-log
POST {{location}}/cars/3972c937-cf8e-4481-9a6a-9bfaf4be5356
Content-Type: application/json

{"command":"enterpitlane"}

### Car exits pit lane
#@no-log
POST {{location}}/cars/3972c937-cf8e-4481-9a6a-9bfaf4be5356
Content-Type: application/json

{"command":"exitpitlane"}

### Car enters pit box
#@no-log
POST {{location}}/cars/3972c937-cf8e-4481-9a6a-9bfaf4be5356
Content-Type: application/json

{"command":"enterpitbox"}

### Car exits pit box
#@no-log
POST {{location}}/cars/3972c937-cf8e-4481-9a6a-9bfaf4be5356
Content-Type: application/json

{"command":"exitpitbox"}

### Change tyre
#@no-log
POST {{location}}/cars/3972c937-cf8e-4481-9a6a-9bfaf4be5356
Content-Type: application/json

{"command":"changetyre"}

### Change nose
#@no-log
POST {{location}}/cars/3972c937-cf8e-4481-9a6a-9bfaf4be5356
Content-Type: application/json

{"command":"changenose"}

###Pit stops
#@no-log
GET {{location}}/pitstops

###Pit stops by car
#@no-log
GET {{location}}/pitstops/3972c937-cf8e-4481-9a6a-9bfaf4be5356

###Start new lap
#@no-log
POST {{location}}/laps
Content-Type: application/json

{"command":"startlap"}

###Deploy safety car
#@no-log
POST {{location}}/laps
Content-Type: application/json

{"command":"deploysafetycar"}

###Recall safety car
#@no-log
POST {{location}}/laps
Content-Type: application/json

{"command":"recallsafetycar"}

###Deploy virtual safety car
#@no-log
POST {{location}}/laps
Content-Type: application/json

{"command":"deployvirtualsafetycar"}

###Recall virtual safety car
#@no-log
POST {{location}}/laps
Content-Type: application/json

{"command":"recallvirtualsafetycar"}