### Initilise race
#@no-log
POST http://localhost:5000/race
Content-Type: application/json

{"trackname":"Silverstone","country":"UK","scheduledstarttime": "2021-02-09T21:05:24Z", "title": "British GP 2021"}

> {% client.global.set("location",response.headers.valueOf("location")) %}

### Start race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "start"}

### Restart race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "restart"}

### Red flag race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "redflag"}

### Open pit lane
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "openpitlane"}

### Close pit lane
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "closepitlane"}

### Stop race
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "stopkk"}

### Change start time
#@no-log
POST {{location}}
Content-Type: application/json

{"command": "delay","proposedracestarttime": "2021-02-09T21:05:24Z"}

### Get a race 
#@no-log
GET {{location}}


### f
OPTIONS {{location}}

### f
HEAD {{location}}


### l

OPTIONS http://localhost:5000/race

### Get a race's cars
#@no-log
GET {{location}}/cars

### Register cars
#@no-log

POST {{location}}/cars
Content-Type: application/json

{"cars":[{"team": "Ferrari","driver": "Charles LeClerc"}]}

### Get a car
#@no-log


GET {{location}}/cars/edd488d5-7609-424c-9090-e0d01e8aad4c

### Register driver
#@no-log
POST http://localhost:5000/drivers
Content-Type: application/json

{"name": "lewis hamiltonfsd"}

### Get drivers
#@no-log
GET http://localhost:5000/drivers

### Get driver
#@no-log
GET http://localhost:5000/drivers/0177ba18-975b-4570-a24c-e2c69a651160